#!/usr/bin/env bash
#instalation of nginx and header name
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n root /usr/share/nginx/html; internal;}" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
