#!/usr/bin/env bash
# se corrige archivo side enable
sudo rm /etc/nginx/site-enable/default
sudo ln -s /etc/nginx/site-available/default /etc/nginx/site-enable/default
sudo pkill nginx
sudo service nginx start