#!/usr/bin/env bash
#When passing the argument start:Starts manage_my_process
#When passing the argument stop: Stops manage_my_process
#When passing the argument restart: Stops manage_my_process


if [ "${1}" == "start" ];then
        ./manage_my_process &
        touch /var/run/my_process.pid 
        echo "$!" > /var/run/my_process.pid
        echo $"manage_my_process started"
        
elif [ "${1}" == "stop" ];then
        kill "$(cat /var/run/my_process.pid)"
        bash -c 'rm -f /var/run/my_process.pid'
        echo $"manage_my_process stopped"
elif [ "${1}" == "restart" ];then
        kill "$(cat /var/run/my_process.pid)"
        bash -c 'rm -f /var/run/my_process.pid'
        ./manage_my_process &
        touch /var/run/my_process.pid 
        echo "$!" > /var/run/my_process.pid
        echo $"manage_my_process restarted"
else
    echo $"Usage: manage_my_process {start|stop|restart}"
fi
