#!/usr/bin/env bash
#read.

input="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f6 f7
do
  echo "The user root is part of the $f3 gang, lives in  $f6 and rides $f7. $f4's place is protected by the passcode $f2, more info about the user here: $f1 The user root is part of the $f3 gang, lives in f6 and rides $f7. $f4's place is protected by the passcode $f2, more info about the user here: $f1"
done < "$input"
