#!/usr/bin/env bash
# displays Holberton School 10 times and Hi.

number=10

while [ $number -gt 0 ];do

    if [ $number == 1 ];then
        echo $"Hi"
    fi
    echo $"Best School"
    (( number -- ))
done
