#!/usr/bin/env bash
# displays good luck and bad luck.

number=0

while [ $number -lt 10 ];do

    if [ $number == 3 ];then
        echo $"bad luck"
    elif [ $number == 7 ];then
        echo $"good luck"
    else
        echo $"Best School"
    fi
    (( number ++ ))
done
