#!/usr/bin/env bash
# displays Hours.

minu=0
hour=0
while [ $hour -le 12 ];do
        echo "Hour: $hour"
        ((hour ++))
        minu=1
    while [ $minu -le 59 ];do
            echo $minu
            (( minu ++ ))
    done

done
